general:
  num_cases: 10
  random_seed: 42
  working_directory: "E:/Master_Thesis_Sumit_Mahindrakar/test_files/Kratos_data_creation"
  sampling_method: "optimal_lhs"

output:
  primal_folder: "primal"
  adjoint_folder: "adjoint"
  primal_prefix: "case_primal"
  adjoint_prefix: "case_adjoint"
  save_config_per_case: true

templates:
  mdpa: "templates/Frame_structure_template.mdpa"
  primal_json: "templates/primal_parameters_template.json"
  adjoint_json: "templates/adjoint_parameters_template.json"
  materials_json: "templates/materials_template.json"

beam_element_ids: [13, 14, 15, 16, 17, 18]

parameters:
  point_load:
    min: 20.0
    max: 100.0
    distribution: "uniform"

  youngs_modulus:
    min: 1.0e10
    max: 1.0e10
    distribution: "loguniform"

  I22:
    min: 1.0e-5
    max: 1.0e-5
    distribution: "loguniform"

  I33:
    min: 1.0e-5
    max: 1.0e-5
    distribution: "loguniform"

  cross_area:
    min: 0.1
    max: 0.1
    distribution: "uniform"

  torsional_inertia:
    min: 1.0e-6
    max: 1.0e-6
    distribution: "loguniform"

  subdivisions:
    min: 12 # 4 or 5
    max: 12
    distribution: "discrete"

  response_location:
    x:
      min: 0.0
      max: 6.0
    y:
      min: 0.0
      max: 0.0
    z:
      min: 3.0
      max: 18.0
    distribution: "uniform"

response:
  stress_type: "MY"
  stress_treatment: "node"
  stress_location: 1

fixed:
  density: 7850.0
  poisson_ratio: 0.3
  gravity: [0.0, 0.0, 0.0]